version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: open
    versions:
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.6
  - dependency-name: semantic-release
    versions:
    - 17.4.2
  - dependency-name: "@semantic-release/git"
    versions:
    - 9.0.0
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: npm
    versions:
    - 6.14.11
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
  - dependency-name: npm-registry-fetch
    versions:
    - 4.0.7
  - dependency-name: lodash
    versions:
    - 4.17.20
