version: '3.5'
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.3.2
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - RUM_ENABLED=true
      - RUM_RATE_LIMIT=10
      - RUM_ALLOW_ORIGINS=['*']
      - RUM_LIBRARY_PATTERN="node_modules|bower_components|~"
      - RUM_EXCLUDE_FROM_GROUPING="^/webpack"
      - RUM_SOURCE_MAPPING_CACHE_EXPIRATION=5m
      - RUM_SOURCE_MAPPING_INDEX_PATTERN="apm-*-sourcemap*"
    command: apm-server -e -E apm-server.rum.enabled=$${RUM_ENABLED} -E apm-server.rum.rate_limit=$${RUM_RATE_LIMIT} -E apm-server.rum.allow_origins=$${RUM_ALLOW_ORIGINS} -E apm-server.rum.library_pattern=$${RUM_LIBRARY_PATTERN} -E apm-server.rum.exclude_from_grouping=$${RUM_EXCLUDE_FROM_GROUPING} -E apm-server.rum.source_mapping.cache.expiration=$${RUM_SOURCE_MAPPING_CACHE_EXPIRATION} -E apm-server.rum.source_mapping.index_pattern=$${RUM_SOURCE_MAPPING_INDEX_PATTERN}
    networks:
      - egendata

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - egendata

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - elasticsearch
    networks:
      - egendata

networks:
  egendata:
    driver: bridge
    name: egendata